### PR TITLE
Add Timestamps

### PR DESCRIPTION
**Pull request by apenasigordev**
Added Timestamps, with just a few changes

Screenshot_20210816-094237_Browser
Screenshot_20210816-094419_Discord-Canary

### CODE REVIEW

**Comment by apenasigordev** [comment]
Remembering: There are still things to update.

**Comment by Gurrman375** [comment]
I can't check it but are the timestamps converting epoch or are they using epoch?

**Comment by apenasigordev** [comment]
you can check [my fork](https://github.com/apenasigordev/Set-Discord-Activity)

**Comment by Gurrman375** [comment]
Why are you setting timestamps to true?

**Comment by apenasigordev** [comment]
> Why are you setting timestamps to true? Timestamps are `startTimestamp` and `endTimestamp` and not `timestamps`.
> image

wut....

True is to enable timestamps when selecting "on".
but in case it doesn't work I can change it...

**Pull request closed without merging**
