### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by NerdBotDiscord**
I created a simple icon on my mobile phone

I hope you enjoy :)

### CODE REVIEW

**Comment by Sainan** [comment]
Certainly better than the joke of a paint image using Comic Sans, but will need some compressing and adjustment of resolution.

**Comment by Sainan** [comment]
Well, it's not transparent, that's unforunately an issue I can't fix.

**Comment by NerdBotDiscord** [comment]
what resolution is used?

**Comment by Sainan** [comment]
128x128

**Comment by NerdBotDiscord** [comment]
OK thanks!

**Comment by NerdBotDiscord** [comment]
Hey, what would be the best font familly to use?

I had used Bold Roboto

**Comment by Sainan** [comment]
Your choice will probably look better than mine.

**Comment by NerdBotDiscord** [comment]
Ok, Lol

**Comment by NerdBotDiscord** [comment]
It's cool?

**Comment by Sainan** [comment]
Looks better than before ¯\\_(ツ)\_/¯

**Pull request merged**
