### PR TITLE
Update popup

### PR DESCRIPTION
**Pull request by NerdBotDiscord**
I recreated the popup ...

I hope it helps 😅

### CODE REVIEW

**Comment by Sainan** [comment]
Bit of a contrast issue with `a:visited`


image

**Comment by NerdBotDiscord** [comment]
I'll try to fix it, it seems to be fast.

**Comment by NerdBotDiscord** [comment]
There, I managed to change the color.

**Comment by NerdBotDiscord** [comment]
Hope this helps ;)

**Pull request merged**
